sonar.verbose=true
sonar.organization=manojdemy-mykey01
sonar.projectKey=manojdemy-mykey01_manojtrends
sonar.projectName=manojtrends
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

